# Generated by Django 6.0.3 on 2026-03-31 19:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Alter campaign_no field in ChzzkCampaign to remove unique constraint."""

    dependencies = [
        ("chzzk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="campaign_no",
            field=models.BigIntegerField(),
        ),
    ]
