# Generated by Django 6.0.3 on 2026-04-01 02:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Migration to alter ChzzkCampaign and ChzzkReward models to change some fields from CharField to TextField."""

    dependencies = [
        ("chzzk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="campaign_reward_type",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="category_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="category_type",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="category_value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="reward_type",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="scrape_status",
            field=models.TextField(default="success"),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="service_id",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="source_api",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="state",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkreward",
            name="campaign_reward_type",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="chzzkreward",
            name="condition_type",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkreward",
            name="reward_type",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="chzzkreward",
            name="title",
            field=models.TextField(),
        ),
    ]
