# Generated by Django 6.0.3 on 2026-04-01 02:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Alter URL fields to allow blank and increase max_length."""

    dependencies = [
        ("chzzk", "0002_alter_chzzkcampaign_campaign_reward_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="account_link_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="image_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="mobile_link_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="chzzkcampaign",
            name="pc_link_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="chzzkreward",
            name="image_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
