services:
  ttvdrops_db:
    image: postgres:18beta3
    container_name: ttvdrops_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ttvdrops
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?You must set POSTGRES_PASSWORD}
      POSTGRES_DB: ttvdrops
      PGDATA: /data
    command: postgres -c config_file=/config/postgresql.conf
    shm_size: 5g
    ports:
      - "5432:5432"
    volumes:
      - /mnt/Docker/Data/ttvdrops/postgresql/data:/data
      - /mnt/Docker/Data/ttvdrops/postgresql/config:/config
    networks:
      - ttvdrops

networks:
  ttvdrops:
    driver: bridge