# Generated by Django 5.2.5 on 2025-08-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='display_name',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='twitch_game_name_c92c15_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['box_art'], name='twitch_game_box_art_498a89_idx'),
        ),
    ]
