# Generated by Django 6.0 on 2026-01-05 20:47
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Alter box_art field to allow null values."""

    dependencies = [
        ("twitch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="box_art",
            field=models.URLField(blank=True, default="", max_length=500, null=True, verbose_name="Box art URL"),
        ),
    ]
