# Generated by Django 5.2.5 on 2025-08-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0002_game_name_alter_game_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropbenefit',
            name='created_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropbenefit',
            name='distribution_type',
            field=models.TextField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='dropbenefit',
            name='name',
            field=models.TextField(blank=True, db_index=True, default='N/A'),
        ),
    ]
