# Generated by Django 6.0 on 2026-01-05 22:29
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    """Remove is_account_connected field and its index from DropCampaign."""

    dependencies = [
        ("twitch", "0002_alter_game_box_art"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dropcampaign",
            name="twitch_drop_is_acco_7e9078_idx",
        ),
        migrations.RemoveField(
            model_name="dropcampaign",
            name="is_account_connected",
        ),
    ]
