# Generated by Django 6.0.1 on 2026-01-09 20:52


from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Allow multiple organizations to own a game.

    For example, Rust is owned by both Facepunch Studios and Twitch Gaming.
    """

    dependencies = [
        ("twitch", "0003_remove_dropcampaign_twitch_drop_is_acco_7e9078_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="game",
            name="twitch_game_owner_i_398fa9_idx",
        ),
        migrations.RemoveIndex(
            model_name="game",
            name="twitch_game_owner_i_7f9043_idx",
        ),
        migrations.AddField(
            model_name="game",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organizations that own this game.",
                related_name="games",
                to="twitch.organization",
                verbose_name="Organizations",
            ),
        ),
        migrations.RemoveField(model_name="game", name="owner"),
    ]
