# Generated by Django 5.2.5 on 2025-08-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0003_alter_dropbenefit_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropcampaign',
            name='end_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropcampaign',
            name='start_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
