# Generated by Django 5.2.4 on 2025-08-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0003_alter_notificationsubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropbenefit',
            name='distribution_type',
            field=models.TextField(db_index=True),
        ),
    ]
