# Generated by Django 5.2.4 on 2025-08-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0004_alter_dropbenefit_distribution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='box_art',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
