# Generated by Django 5.2.5 on 2025-08-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0004_alter_dropcampaign_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebaseddrop',
            name='end_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timebaseddrop',
            name='required_minutes_watched',
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='timebaseddrop',
            name='start_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
