# Generated by Django 5.2.5 on 2025-09-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0006_alter_dropbenefit_options_alter_dropcampaign_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='unique_game_slug',
        ),
    ]
