# Generated by Django 6.0.2 on 2026-02-09 19:04
from __future__ import annotations

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    "Alter model options to use prefetch_manager as the base manager and set default ordering for better performance and consistent query results."  # noqa: E501

    dependencies = [
        ("twitch", "0007_rename_operation_name_to_operation_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"base_manager_name": "prefetch_manager", "ordering": ["display_name"]},
        ),
        migrations.AlterModelOptions(
            name="chatbadge",
            options={"base_manager_name": "prefetch_manager", "ordering": ["badge_set", "badge_id"]},
        ),
        migrations.AlterModelOptions(
            name="chatbadgeset",
            options={"base_manager_name": "prefetch_manager", "ordering": ["set_id"]},
        ),
        migrations.AlterModelOptions(
            name="dropbenefit",
            options={"base_manager_name": "prefetch_manager", "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="dropbenefitedge",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="dropcampaign",
            options={"base_manager_name": "prefetch_manager", "ordering": ["-start_at"]},
        ),
        migrations.AlterModelOptions(
            name="game",
            options={"base_manager_name": "prefetch_manager", "ordering": ["display_name"]},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"base_manager_name": "prefetch_manager", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="rewardcampaign",
            options={"base_manager_name": "prefetch_manager", "ordering": ["-starts_at"]},
        ),
        migrations.AlterModelOptions(
            name="timebaseddrop",
            options={"base_manager_name": "prefetch_manager", "ordering": ["start_at"]},
        ),
        migrations.AlterModelOptions(
            name="twitchgamedata",
            options={"base_manager_name": "prefetch_manager", "ordering": ["name"]},
        ),
        migrations.AlterModelManagers(
            name="channel",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="chatbadge",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="chatbadgeset",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dropbenefit",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dropbenefitedge",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dropcampaign",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="game",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organization",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="rewardcampaign",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="timebaseddrop",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="twitchgamedata",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
