# Generated by Django 6.0.2 on 2026-02-09 19:05
from __future__ import annotations

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    "Alter ChatBadge.badge_set to use auto_prefetch.ForeignKey and update related fields to use auto_prefetch.ForeignKey as well for better performance."  # noqa: E501

    dependencies = [
        ("twitch", "0008_alter_channel_options_alter_chatbadge_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbadge",
            name="badge_set",
            field=auto_prefetch.ForeignKey(
                help_text="The badge set this badge belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to="twitch.chatbadgeset",
                verbose_name="Badge Set",
            ),
        ),
        migrations.AlterField(
            model_name="dropbenefitedge",
            name="benefit",
            field=auto_prefetch.ForeignKey(
                help_text="The benefit in this relationship.",
                on_delete=django.db.models.deletion.CASCADE,
                to="twitch.dropbenefit",
            ),
        ),
        migrations.AlterField(
            model_name="dropbenefitedge",
            name="drop",
            field=auto_prefetch.ForeignKey(
                help_text="The time-based drop in this relationship.",
                on_delete=django.db.models.deletion.CASCADE,
                to="twitch.timebaseddrop",
            ),
        ),
        migrations.AlterField(
            model_name="dropcampaign",
            name="game",
            field=auto_prefetch.ForeignKey(
                help_text="Game associated with this campaign.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drop_campaigns",
                to="twitch.game",
                verbose_name="Game",
            ),
        ),
        migrations.AlterField(
            model_name="rewardcampaign",
            name="game",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="Game associated with this reward campaign (if any).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reward_campaigns",
                to="twitch.game",
            ),
        ),
        migrations.AlterField(
            model_name="timebaseddrop",
            name="campaign",
            field=auto_prefetch.ForeignKey(
                help_text="The campaign this drop belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_based_drops",
                to="twitch.dropcampaign",
            ),
        ),
        migrations.AlterField(
            model_name="twitchgamedata",
            name="game",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="Optional link to the local Game record for this Twitch game.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="twitch_game_data",
                to="twitch.game",
                verbose_name="Game",
            ),
        ),
    ]
