# Generated by Django 5.2.5 on 2025-09-04 22:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0008_rename_created_at_dropcampaign_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropcampaign',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dropbenefit',
            index=models.Index(condition=models.Q(('is_ios_available', True)), fields=['is_ios_available'], name='benefit_ios_available_idx'),
        ),
        migrations.AddIndex(
            model_name='dropcampaign',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='campaign_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='dropcampaign',
            index=models.Index(condition=models.Q(('end_at__isnull', False), ('start_at__isnull', False)), fields=['start_at', 'end_at'], name='campaign_active_partial_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(condition=models.Q(('owner__isnull', False)), fields=['owner'], name='game_owner_partial_idx'),
        ),
        migrations.AddIndex(
            model_name='timebaseddrop',
            index=models.Index(fields=['campaign', 'start_at', 'required_minutes_watched'], name='twitch_time_campaig_4cc3b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='dropcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='campaign_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='timebaseddrop',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='drop_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='timebaseddrop',
            constraint=models.CheckConstraint(condition=models.Q(('required_minutes_watched__isnull', True), ('required_minutes_watched__gt', 0), _connector='OR'), name='drop_positive_minutes'),
        ),
    ]
