# Generated by Django 5.2.5 on 2025-09-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0009_postgresql_optimizations_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropbenefit',
            name='id',
            field=models.CharField(help_text='Unique Twitch identifier for the benefit.', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Game ID'),
        ),
        migrations.AlterField(
            model_name='timebaseddrop',
            name='id',
            field=models.CharField(help_text='Unique Twitch identifier for the time-based drop.', max_length=255, primary_key=True, serialize=False),
        ),
    ]
