# Generated by Django 5.2.5 on 2025-09-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0010_alter_dropbenefit_id_alter_game_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timebaseddrop',
            name='drop_positive_minutes',
        ),
        migrations.AddConstraint(
            model_name='timebaseddrop',
            constraint=models.CheckConstraint(condition=models.Q(('required_minutes_watched__isnull', True), ('required_minutes_watched__gte', 0), _connector='OR'), name='drop_positive_minutes'),
        ),
    ]
