# Generated by Django 6.0.3 on 2026-03-09 18:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add box art MIME type and size fields to Game, and backfill existing data."""

    dependencies = [
        ("twitch", "0012_dropcampaign_operation_names_gin_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="box_art_mime_type",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="MIME type of the cached box art image (e.g., 'image/png').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="box_art_size_bytes",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                help_text="File size of the cached box art image in bytes.",
                null=True,
            ),
        ),
    ]
