# Generated by Django 5.2.6 on 2025-09-12 22:03

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0013_dropcampaign_allow_is_enabled_channel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='dropbenefit',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dropbenefitedge',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='dropcampaign',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-start_at']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='notificationsubscription',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='timebaseddrop',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['start_at']},
        ),
        migrations.AlterModelManagers(
            name='channel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dropbenefit',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dropbenefitedge',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dropcampaign',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='notificationsubscription',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='timebaseddrop',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
