# Generated by Django 6.0.3 on 2026-03-09 18:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add image MIME type and size fields to DropCampaign, and backfill existing data."""

    dependencies = [
        ("twitch", "0013_game_box_art_mime_type_game_box_art_size_bytes"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropcampaign",
            name="image_mime_type",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="MIME type of the cached campaign image (e.g., 'image/png').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dropcampaign",
            name="image_size_bytes",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                help_text="File size of the cached campaign image in bytes.",
                null=True,
            ),
        ),
    ]
