# Generated by Django 6.0.3 on 2026-03-19 19:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add a new field `is_fully_imported` to the `DropCampaign` model to track whether all related images and formats have been imported and are ready for display. This field will help us filter out campaigns that are not yet fully imported in our views and APIs, ensuring that only complete campaigns are shown to users."""

    dependencies = [
        ("twitch", "0014_dropcampaign_image_mime_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropcampaign",
            name="is_fully_imported",
            field=models.BooleanField(
                default=False,
                help_text="True if all images and formats are imported and ready for display.",
            ),
        ),
    ]
