# Generated by Django 5.2.6 on 2025-09-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitch', '0016_add_local_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropbenefit',
            name='image_file',
            field=models.FileField(blank=True, help_text='Locally cached benefit image served from this site.', null=True, upload_to='benefits/images/'),
        ),
        migrations.AlterField(
            model_name='dropcampaign',
            name='image_file',
            field=models.FileField(blank=True, help_text='Locally cached campaign image served from this site.', null=True, upload_to='campaigns/images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='box_art_file',
            field=models.FileField(blank=True, help_text='Locally cached box art image served from this site.', null=True, upload_to='games/box_art/'),
        ),
    ]
