# Generated by Django 6.0.4 on 2026-04-10 23:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add an index on DropBenefit for distribution_type and name."""

    dependencies = [
        ("twitch", "0016_mark_all_drops_fully_imported"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dropbenefit",
            index=models.Index(
                fields=["distribution_type", "name"],
                name="twitch_drop_distrib_70d961_idx",
            ),
        ),
    ]
