# Generated by Django 6.0.4 on 2026-04-10 23:18

from django.db import migrations


class Migration(migrations.Migration):
    """Rename some indexes on DropCampaign and RewardCampaign to be more descriptive."""

    dependencies = [
        ("twitch", "0017_dropbenefit_twitch_drop_distrib_70d961_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dropcampaign",
            new_name="tw_drop_start_desc_idx",
            old_name="twitch_drop_start_a_929f09_idx",
        ),
        migrations.RenameIndex(
            model_name="dropcampaign",
            new_name="tw_drop_start_end_idx",
            old_name="twitch_drop_start_a_6e5fb6_idx",
        ),
        migrations.RenameIndex(
            model_name="dropcampaign",
            new_name="tw_drop_start_end_game_idx",
            old_name="twitch_drop_start_a_b02d4c_idx",
        ),
        migrations.RenameIndex(
            model_name="rewardcampaign",
            new_name="tw_reward_starts_desc_idx",
            old_name="twitch_rewa_starts__4df564_idx",
        ),
        migrations.RenameIndex(
            model_name="rewardcampaign",
            new_name="tw_reward_starts_ends_idx",
            old_name="twitch_rewa_starts__dd909d_idx",
        ),
    ]
