# Generated by Django 6.0.4 on 2026-04-10 23:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add indexes to optimize queries for the campaign list view."""

    dependencies = [
        (
            "twitch",
            "0018_rename_twitch_drop_start_a_929f09_idx_tw_drop_start_desc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dropcampaign",
            index=models.Index(
                fields=["is_fully_imported", "-start_at"],
                name="tw_drop_imported_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dropcampaign",
            index=models.Index(
                fields=["is_fully_imported", "start_at", "end_at"],
                name="tw_drop_imported_start_end_idx",
            ),
        ),
    ]
