# Generated by Django 6.0.4 on 2026-05-09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Allow longer campaign URLs returned by Twitch imports."""

    dependencies = [
        ("twitch", "0022_dropcampaign_tw_drop_game_end_desc_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropcampaign",
            name="account_link_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to link a Twitch account for the campaign.",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="dropcampaign",
            name="details_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL with campaign details.",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="dropcampaign",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to an image representing the campaign.",
                max_length=2000,
            ),
        ),
    ]
