# Generated by Django 6.0.6 on 2026-06-14 13:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Adds a `data_source` field to DropCampaign and RewardCampaign to track the origin of imported campaign data.

    This allows us to distinguish between campaigns imported by different tools (e.g. TwitchDropsMiner vs. SunkwiBOT/twitch-drops-api) and can be useful for debugging, analytics, or future migrations that may need to handle data differently based on its source.
    """

    dependencies = [
        ("twitch", "0023_alter_dropcampaign_url_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropcampaign",
            name="data_source",
            field=models.TextField(
                choices=[
                    ("TwitchDropsMiner", "TwitchDropsMiner"),
                    ("SunkwiBOT/twitch-drops-api", "SunkwiBOT/twitch-drops-api"),
                ],
                default="TwitchDropsMiner",
                help_text="Identifies the origin tool/script that imported this campaign data.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="rewardcampaign",
            name="data_source",
            field=models.TextField(
                choices=[
                    ("TwitchDropsMiner", "TwitchDropsMiner"),
                    ("SunkwiBOT/twitch-drops-api", "SunkwiBOT/twitch-drops-api"),
                ],
                default="TwitchDropsMiner",
                help_text="Identifies the origin tool/script that imported this campaign data.",
                max_length=50,
            ),
        ),
    ]
