# Generated by Django 6.0.8 on 2026-08-24 17:29

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Create the Reward model for individual rewards inside reward campaigns."""

    dependencies = [
        ("twitch", "0024_dropcampaign_data_source_rewardcampaign_data_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "twitch_id",
                    models.TextField(
                        editable=False,
                        help_text="The Twitch ID for this reward.",
                        unique=True,
                    ),
                ),
                ("name", models.TextField(help_text="Name of the reward.")),
                (
                    "banner_image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to the reward's banner image.",
                        max_length=500,
                    ),
                ),
                (
                    "thumbnail_image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to the reward's thumbnail image.",
                        max_length=500,
                    ),
                ),
                (
                    "earnable_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datetime until which the reward can be earned.",
                        null=True,
                    ),
                ),
                (
                    "redemption_instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Instructions for redeeming the reward.",
                    ),
                ),
                (
                    "redemption_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to redeem the reward.",
                        max_length=500,
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this reward record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this reward record was last updated.",
                    ),
                ),
                (
                    "reward_campaign",
                    auto_prefetch.ForeignKey(
                        help_text="The reward campaign this reward belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="twitch.rewardcampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["earnable_until", "name"],
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "indexes": [
                    models.Index(
                        fields=["twitch_id"],
                        name="twitch_rewa_twitch__d45837_idx",
                    ),
                    models.Index(
                        fields=["reward_campaign"],
                        name="twitch_rewa_reward__60d965_idx",
                    ),
                    models.Index(
                        fields=["earnable_until"],
                        name="twitch_rewa_earnabl_11159a_idx",
                    ),
                    models.Index(fields=["name"], name="twitch_rewa_name_5d16e1_idx"),
                    models.Index(
                        fields=["reward_campaign", "earnable_until"],
                        name="twitch_rewa_reward__367d71_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
