# Generated by Django 6.0.8 on 2026-08-24 18:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add local image caching fields to the Reward model."""

    dependencies = [
        ("twitch", "0025_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="reward",
            name="image_file",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                help_text="Locally cached reward image served from this site.",
                null=True,
                upload_to="rewards/images/",
                width_field="image_width",
            ),
        ),
        migrations.AddField(
            model_name="reward",
            name="image_height",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                help_text="Height of cached image in pixels.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reward",
            name="image_width",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                help_text="Width of cached image in pixels.",
                null=True,
            ),
        ),
    ]
