# Generated by Django 6.0.3 on 2026-03-19 19:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """Add is_fully_imported field to KickDropCampaign to track import status."""

    dependencies = [
        ("kick", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kickdropcampaign",
            name="is_fully_imported",
            field=models.BooleanField(
                default=False,
                help_text="True if all images and formats are imported and ready for display.",
            ),
        ),
    ]
