name: Run Pytest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 14 * * 0" # Run weekly at 14:00 UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DJANGO_DEBUG: False
      DJANGO_SECRET_KEY: 1234567890

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - uses: astral-sh/setup-uv@v7
      - run: uv sync --all-extras --dev
      - run: uv run pytest
